name: haiternak_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  dots_indicator: 2.1.0
  delayed_display: 2.0.0
  flutter_svg: 1.1.5
  carousel_slider: 4.1.1
  get_cli: ^1.8.1
  flutter: 
    sdk: flutter
  icony: ^1.0.5
  icon: ^2.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

